version: "3.8"
services:
    match-maker:
        build: .
        environment:
            - VIRTUAL_HOST=groupmaker.engscitools.ca
        # ports:
        #     - "5000:80"
        restart: unless-stopped
        network_mode: "bridge"
